"""PDF export of an AI assessment."""

import io
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

INK = colors.HexColor("#1d1d1f")
MUTED = colors.HexColor("#6e6e73")
HAIRLINE = colors.HexColor("#d2d2d7")
FILL = colors.HexColor("#f5f5f7")


def assessment_pdf(ctx: dict, ai: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=60, rightMargin=60, topMargin=60, bottomMargin=48)
    base = getSampleStyleSheet()
    title = ParagraphStyle("t", parent=base["Title"], fontName="Helvetica-Bold", fontSize=22, textColor=INK, alignment=0, spaceAfter=4)
    sub = ParagraphStyle("s", parent=base["Normal"], fontSize=9, textColor=MUTED, spaceAfter=18)
    h2 = ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=13, textColor=INK, spaceBefore=14, spaceAfter=6)
    h3 = ParagraphStyle("h3", parent=base["Heading3"], fontName="Helvetica-Bold", fontSize=10.5, textColor=INK, spaceBefore=6, spaceAfter=2)
    body = ParagraphStyle("b", parent=base["Normal"], fontSize=9.5, leading=13.5, textColor=INK, spaceAfter=4)
    foot = ParagraphStyle("f", parent=base["Normal"], fontSize=7.5, textColor=MUTED, alignment=TA_CENTER)

    def p(text, style=body):
        return Paragraph(escape(str(text)).replace("\n", "<br/>"), style)

    name = ctx["fundamental"]["profile"]["name"]
    price = ctx["technical"]["quote"]["price"]
    story = [
        p(f"{ctx['symbol']} Investment Assessment", title),
        p(f"{name} · Generated {datetime.now():%d %b %Y, %H:%M} · {ai.get('model', '')}", sub),
    ]

    summary_rows = [
        ["Recommendation", ai["recommendation"]],
        ["Confidence", f"{ai['confidence']} / 10"],
        ["Time horizon", ai["time_horizon"]],
        ["Price at assessment", f"{price:,.2f}"],
        ["Price target", f"{ai['price_target']:,.2f}" if ai.get("price_target") else "—"],
    ]
    table = Table(summary_rows, colWidths=[1.9 * inch, 4.2 * inch])
    table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
        ("BACKGROUND", (0, 0), (-1, -1), FILL),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, HAIRLINE),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story += [table, p("Summary", h2), p(ai["summary"]), p("Position advice", h2), p(ai["position_advice"])]

    story.append(p("Reasoning", h2))
    for i, step in enumerate(ai.get("steps", []), 1):
        story += [p(f"{i}. {step['title']}", h3), p(step["content"])]

    for heading, items in (("Strengths", ai.get("strengths", [])), ("Risks", ai.get("risks", []))):
        if items:
            story.append(p(heading, h2))
            story += [p(f"•  {item}") for item in items]

    story += [Spacer(1, 24), p("Generated by Portfolio Dashboard. For information only — not financial advice.", foot)]
    doc.build(story)
    return buf.getvalue()
